#!/usr/local/bin/perl

# Create IFM test programs.

$ifmprog = shift;

foreach $ifmfile (@ARGV) {
    die "Can't find $ifmfile\n" unless -f $ifmfile;

    # Build test and expected results files.
    $prefix = $ifmfile;
    $prefix =~ s/\.ifm$//;
    $testfile = $prefix . ".test";
    $expfile = $prefix . ".exp";
    $listfile = $prefix . ".list";

    # Skip it if up to date.
    next if -f $testfile
	&& -M $testfile < -M $ifmfile
	    && -M $testfile < -M $0;

    # Read test input.
    open(IN, $ifmfile) or die "Can't open $ifmfile: $!\n";
    @prog = <IN>;
    close IN;

    # Find output required.
    if ($ifmfile =~ /^(.+)-/) {
	$output = $1;
    } else {
	die "Can't determine output required: $ifmfile\n";
    }

    die "Invalid output requested: $ifmfile\n"
	unless $output =~ /^(map|item|task)/;

    # Write test program.
    open(OUT, "> $testfile") or die "Can't open $testfile: $!\n";

    print OUT "#! /bin/sh\n";
    print OUT "$ifmprog -w -$output -format raw <<END\n";
    print OUT @prog;
    print OUT "END\n";
    close OUT;

    chmod 0775, $testfile;

    # Create expected results.
    system "$ifmprog -w -$output -format raw -o $expfile $ifmfile";

    # If task test, create verbose task list.
    system "$ifmprog -w -$output -format text -o $listfile $ifmfile"
	if $output =~ /^task/;

    # Er... that's it.
    print "Created $testfile\n";
}
