
task: 3
name: Get thing
room: 0

task: 4
name: Do first thing
tag: first
room: 0

task: 9
name: Move to Room 2
room: 1
cmd: E

task: 5
name: Do second thing
tag: second
room: 1

task: 10
name: Move to Room 1
room: 0
cmd: W

task: 8
name: Get thing
room: 0

task: 11
name: Move to Room 2
room: 1
cmd: E

task: 12
name: Move to Room 3
room: 2
cmd: E

task: 6
name: Win
room: 2

task: 13
name: Drop thing
