
task: 8
name: Move to Corridor
room: 2
cmd: W

task: 9
name: Move to Corridor
room: 3
cmd: W

task: 10
name: Move to Corridor
room: 4
cmd: W

task: 11
name: Move to Treasure Room
room: 5
cmd: W

task: 6
name: Get diamond
room: 5
score: 1
note: Not used for anything yet

task: 12
name: Move to Corridor
room: 4
cmd: E

task: 13
name: Move to Corridor
room: 3
cmd: N

task: 14
name: Move to Corridor
room: 2
cmd: E

task: 15
name: Move to Start
room: 0
cmd: E

task: 16
name: Move to Bottom of Chute
room: 1
cmd: S

task: 7
name: Win the game
room: 1
score: 10
