
task: 9
name: Move to Closet
room: 2
cmd: S

task: 6
name: Get torch
room: 2

task: 10
name: Move to Start
room: 0
cmd: N

task: 11
name: Move to Cell
room: 1
cmd: E

task: 5
name: Get treasure
room: 1
score: 1

task: 12
name: Move to Start
room: 0
cmd: W

task: 7
name: Pull the stick
tag: pull_stick
room: 0

task: 4
name: Get stick
room: 0
score: 1
note: Props cell door open

task: 13
name: Move to Freedom
room: 3
cmd: W

task: 8
name: Win the game
room: 3

task: 14
name: Drop stick

task: 15
name: Drop treasure
