
task: 3
name: Get hammer
room: 0

task: 8
name: Move to Room 2
room: 1
cmd: N

task: 6
name: Room2
tag: room2
room: 1

task: 4
name: Get tongs
room: 1

task: 9
name: Move to Room 1
room: 0
cmd: S

task: 5
name: Room1
tag: room1
room: 0

task: 10
name: Move to Room 2
room: 1
cmd: N

task: 11
name: Move to Room 3
room: 2
cmd: N

task: 7
name: Room3
tag: room3
room: 2

task: 12
name: Drop hammer

task: 13
name: Drop tongs
