=head1 NAME

tkifm -- simple graphical front end to ifm(1)

=head1 SYNOPSIS

tkifm [file]

=head1 DESCRIPTION

B<tkifm> is a graphical front end to ifm(1), the Interactive Fiction
Mapper, written in Tcl/Tk.  It provides a text editing window in which you
map out your game using B<ifm> commands, and a set of menus to view
things.  The various features are as follows:

=over 4

=item Text editing window

This is the main window, where you type B<ifm> commands.  It provides all
the usual text editing command bindings that come with the Tcl/Tk text
widget.

=item File menu

The standard set of file commands: New, Open, Save, Save-As, Print (to
PostScript), Quit.  There's also a command called Redraw, which invokes
B<ifm> on the current file again.  Normally you don't have to use this
(it's done whenever you open a new file or save the current one), but if
you change your initialisation file (see below) the changes won't be
noticed unless you do a Redraw.

=item Map menu

For each map section in your map, a menu entry appears here.  Selecting it
will draw the appropriate map in another window.

=item Item menu

This contains a single menu item, which displays a list of items in another
window.

=item Task menu

This contains a single menu item, which displays a high-level walkthrough
of the game in another window.

=item Help menu

At the moment this just displays a small info panel about B<tkifm>.

=back

=head1 CUSTOMIZATION

On startup, B<tkifm> reads an initialisation file in your home directory
(the one pointed at by the B<HOME> environment variable).  On Unix systems
it is called F<.tkifmrc>, and on Win32 systems it is called F<tkifm.ini>.
From there, using Tcl commands, you can set various things that affect the
appearance of the program.  Here's an example file showing the valid
variables, their format and defaults.

    # Example tkifm init file.

    # Edit window dimensions.
    set ifm(editwidth) 80
    set ifm(editheight) 24

    # Editing font.
    set ifm(editfont) {Courier 12 bold}

    # Edit window colours.
    set ifm(editforeground) black
    set ifm(editbackground) wheat

    # Text window (items and tasks) dimensions.
    set ifm(textwidth) 50
    set ifm(textheight) 30

    # Text window font.
    set ifm(textfont) {Times 12 bold}

    # Text window colours.
    set ifm(textforeground) black
    set ifm(textbackground) wheat

    # Whether to allow tearoff menus.
    set ifm(tearoff) 1

=head1 ERRORS AND WARNINGS

Any errors or warnings that occur when invoking B<ifm> will be displayed in
a dialog.  The current line of the text window will be changed to point at
the error or warning line (if appropriate).

=head1 SEE ALSO

ifm(1)

=head1 AUTHOR

Glen Hutchings

=cut
