# Common Makefile targets.

IFM = $(top_srcdir)/src/ifm $(IFMOPTS)
IFMOPTS = -I $(top_srcdir)/lib -s version="$(VERSION)" -S helvetica

docdir = $(prefix)/doc
ifmdocdir = $(docdir)/ifm

# Show recent source changes.

DAYS = 7

log:;	@ echo
	@ echo Finding source changes in the last $(DAYS) days...
	@ echo
	@ cvslog $(DAYS)
