=head1 ENVIRONMENT

These environment variables are used by B<IFM>:

=over 12

=item B<HOME>

Pathname of your home directory (used to find personal init file).

=item B<IFMPATH>

Colon-separated list of directories used to search for library files.

=back

=for inf skipnode

=head1 SEE ALSO

tkifm(1), scr2ifm(1)

=for inf skipnode

=head1 AUTHOR

Glen Hutchings (zondo@hunting2.demon.co.uk)

=cut
