/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 90
#define YY_END_OF_BUFFER 91
static yyconst short int yy_accept[278] =
    {   0,
        0,    0,    0,    0,   91,   89,    2,    3,    4,    1,
       89,   89,   87,   89,   84,   84,   84,   84,   10,   14,
       84,   84,   84,   84,   84,   84,   84,   84,   41,   84,
       84,   84,   57,   84,   73,   77,   84,    4,   89,    2,
        1,   85,   86,    0,   87,   88,    0,   84,   84,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   84,   84,   84,   25,   84,   84,   29,   30,   84,
       84,   84,   84,   84,   84,   84,   42,   84,   51,   84,
       84,   84,   84,   84,   84,   84,   60,   84,   84,   84,
       67,   84,   84,   72,   84,   76,   84,   84,   29,    0,

        0,   85,   83,   84,    6,    7,   84,    9,   11,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   22,   84,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   84,
       84,   40,   84,   84,   84,   84,   84,   84,   84,   53,
       84,   84,   84,   84,   84,   84,   84,   84,   84,   68,
       84,   84,   84,   84,   84,   84,   84,   84,    0,    0,
       83,   84,   84,   12,   13,   15,   84,   84,   18,   84,
       84,   21,   23,   26,   84,   84,   31,   32,   33,   34,
       84,   84,   37,   38,   39,   43,   84,   46,   84,   84,
       50,   84,   84,   84,   56,   58,   84,   84,   84,   84,

       84,   69,   84,   84,   84,   84,   78,   79,   84,    0,
       81,    0,   82,    5,   84,   84,   84,   84,   84,   24,
       84,   84,   35,   84,   84,   84,   47,   84,   84,   84,
       59,   61,   84,   65,   66,   70,   71,   74,   75,   84,
        8,   84,   17,   19,   20,   27,   28,   36,   44,   45,
       84,   84,   52,   54,   84,   84,   84,   84,   84,   84,
       84,   84,   55,   84,   84,   64,   80,   16,   84,   84,
       84,   84,   48,   49,   62,   63,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    5,    6,    7,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    8,    1,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    1,    1,   10,
       11,   12,    1,    1,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,   13,   13,   13,
        1,    1,    1,    1,   13,    1,   14,   15,   16,   17,

       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[40] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    4,    5,    1,
        1,    6,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7
    } ;

static yyconst short int yy_base[286] =
    {   0,
        0,  533,   35,   36,  554,  556,   40,  556,  556,    0,
        0,  544,   39,  540,  543,   35,   41,   42,   43,   49,
       44,   59,   47,   62,   45,   70,   76,   71,   75,   72,
       83,   84,  110,   93,  100,   92,   89,    0,    0,  121,
        0,    0,  541,  540,  111,  556,    0,  540,   97,   88,
      123,  125,  124,  126,  127,  128,  132,  134,  137,  139,
      129,  140,  141,  142,  147,  150,  144,  539,  152,  154,
      157,  161,  164,  165,  171,  173,  176,  196,  538,  177,
      174,  175,  178,  181,  179,  182,  537,  188,  193,  192,
      536,  204,  205,  535,  209,  534,  207,  208,   48,  536,

      528,    0,    0,  210,  531,  530,  191,  529,  528,  224,
      225,  212,  226,  229,  227,  235,  180,  236,  527,  232,
      238,  244,  240,  241,  245,  247,  248,  251,  255,  256,
      261,  526,  257,  262,  265,  263,  270,  274,  277,  525,
      279,  280,  281,  282,  285,  287,  283,  288,  290,  524,
      293,  294,  296,  314,  289,  297,  302,  300,  324,  326,
        0,  316,  323,  523,  522,  521,  301,  327,  520,  325,
      330,  519,  328,  518,  331,  329,  517,  516,  515,  514,
      332,  333,  513,  512,  511,  510,  334,  509,  335,  338,
      508,  337,  340,  345,  507,  506,  344,  355,  356,  336,

      362,  505,  363,  364,  365,  366,  504,  503,  367,  383,
      556,  385,  556,  502,  371,  369,  373,  375,  382,  501,
      384,  385,  500,  389,  390,  391,  386,  392,  397,  394,
      498,  401,  409,  495,  492,  482,  478,  470,  467,  412,
      466,  408,  462,  461,  457,  456,  455,  454,  453,  452,
      413,  416,  450,  449,  418,  424,  423,  420,  431,  432,
      427,  434,  448,  435,  436,  447,  446,  445,  438,  439,
      440,  443,  444,  405,  400,  298,  556,  476,  190,  480,
      487,  494,  497,   54,  500
    } ;

static yyconst short int yy_def[286] =
    {   0,
      277,    1,    1,    1,  277,  277,  277,  277,  277,  278,
      279,  277,  277,  277,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  281,  282,  277,
      278,  283,  277,  277,  277,  277,  284,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  281,

      282,  283,  285,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  277,  277,
      285,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,

      280,  280,  280,  280,  280,  280,  280,  280,  280,  277,
      277,  277,  277,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,  280,  280,  280,  280,
      280,  280,  280,  280,  280,  280,    0,  277,  277,  277,
      277,  277,  277,  277,  277
    } ;

static yyconst short int yy_nxt[596] =
    {   0,
        6,    7,    8,    7,    9,   10,   11,   12,   13,    6,
       14,    6,   15,   16,   17,   18,   19,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   15,
       32,   33,   34,   35,   15,   36,   15,   15,   15,   38,
       38,   40,   47,   40,   39,   39,   44,   45,   47,   47,
       47,   47,   47,   49,   47,   47,   47,   37,   52,   50,
      103,   51,   57,  158,   54,   60,   47,   53,   66,   47,
       55,   61,   70,   56,   62,   58,   63,   47,   47,   47,
       64,   67,   47,   47,   76,   59,   65,   71,   68,   72,
       47,   47,   77,   73,   69,   47,   47,   74,   80,   47,

       47,   83,   78,   75,   47,   81,   92,   47,   67,   97,
       79,   84,  105,   98,   93,   99,   82,   47,   44,   45,
       94,   69,   40,   85,   40,   86,   95,   87,   96,  104,
       47,   47,   47,   47,   47,   47,   47,   88,   89,   47,
      108,   47,   90,  107,   47,   91,   47,   47,   47,   47,
      113,   47,  114,  117,   47,  111,  109,   47,  115,   47,
      106,   47,  110,  112,   47,  116,  122,  118,   47,  124,
      123,   47,   47,  119,  126,  125,  120,  128,   47,  121,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
      129,  130,  127,  133,  139,   47,   42,  144,   47,   47,

       47,  132,  131,   47,  171,  148,  140,  142,  143,  145,
      147,   47,   47,  141,   47,   47,   47,   47,  163,   47,
      134,  146,  135,  150,  136,  154,  137,  162,  138,  149,
      152,   47,   47,   47,   47,  151,   47,  153,  156,   47,
      157,  155,   47,   47,  166,   47,  168,   47,   47,  173,
      164,   47,   47,  165,   47,   47,  170,  167,   47,  169,
      175,  172,   47,   47,   47,  174,  177,  176,   47,   47,
       47,  178,   47,  186,  182,  179,  189,   47,  184,  183,
      180,   47,  188,  187,   47,  181,   47,   47,   47,   47,
       47,  191,   47,  185,   47,   47,   47,   47,  199,  196,

       47,   47,  190,   47,   47,   47,  195,   47,   47,   47,
      206,  203,  192,  194,  201,  197,  202,  193,  200,  198,
      204,   47,  208,   47,  209,  210,  211,  212,  213,  207,
       47,  205,   47,  216,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,  214,   47,  221,  223,
      228,   47,   47,  215,  220,  217,  218,  219,  227,  222,
      225,  231,   47,   47,  229,  224,  230,  226,  234,   47,
       47,   47,   47,   47,   47,  232,   47,  233,   47,  235,
       47,  237,   47,  238,  210,  211,  212,  213,  241,   47,
      239,   47,   47,   47,  236,  244,   47,   47,   47,   47,

      240,   47,  247,  251,   47,  243,  242,   47,   47,  248,
      246,  250,   47,  249,  254,   47,   47,  245,  256,   47,
       47,  252,  258,   47,  255,   47,  261,   47,  259,  253,
       47,   47,  260,  262,   47,  263,  257,  264,   47,   47,
      265,   47,   47,   47,  266,   47,   47,   47,  267,  268,
       47,   47,   47,   47,   47,   47,   47,   47,  269,   47,
       47,   47,   47,   47,   47,  270,  271,  272,   47,   47,
      273,  274,  275,   47,   47,  276,   41,   47,   41,   41,
       41,   41,   41,   48,   48,   47,   48,  100,  100,   47,
      100,  100,  100,  100,  101,  101,  101,  101,  101,   47,

      101,  102,   47,  102,  161,   47,  161,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   47,   47,   47,   47,   47,   47,   47,  160,
      159,   47,   47,   47,   47,   47,   47,   47,   43,   43,
       47,   46,   43,  277,   37,    5,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277

    } ;

static yyconst short int yy_chk[596] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        4,    7,   16,    7,    3,    4,   13,   13,   17,   18,
       19,   21,   25,   16,   23,   99,   20,    4,   17,   16,
      284,   16,   20,   99,   19,   21,   22,   18,   23,   24,
       19,   21,   25,   19,   21,   20,   22,   26,   28,   30,
       22,   24,   29,   27,   28,   20,   22,   26,   24,   27,
       31,   32,   29,   27,   24,   50,   37,   27,   30,   36,

       34,   32,   29,   27,   49,   30,   34,   35,   37,   36,
       29,   32,   50,   36,   34,   37,   31,   33,   45,   45,
       34,   37,   40,   33,   40,   33,   35,   33,   35,   49,
       51,   53,   52,   54,   55,   56,   61,   33,   33,   57,
       53,   58,   33,   52,   59,   33,   60,   62,   63,   64,
       58,   67,   59,   61,   65,   56,   54,   66,   59,   69,
       51,   70,   55,   57,   71,   60,   66,   62,   72,   69,
       67,   73,   74,   63,   71,   70,   64,   73,   75,   65,
       76,   81,   82,   77,   80,   83,   85,  117,   84,   86,
       73,   74,   72,   77,   80,   88,  279,   85,  107,   90,

       89,   76,   75,   78,  117,   90,   81,   83,   84,   86,
       89,   92,   93,   82,   97,   98,   95,  104,  107,  112,
       78,   88,   78,   92,   78,   95,   78,  104,   78,   90,
       93,  110,  111,  113,  115,   92,  114,   93,   97,  120,
       98,   95,  116,  118,  112,  121,  114,  123,  124,  120,
      110,  122,  125,  111,  126,  127,  116,  113,  128,  115,
      122,  118,  129,  130,  133,  121,  124,  123,  131,  134,
      136,  125,  135,  133,  129,  126,  136,  137,  131,  130,
      127,  138,  135,  134,  139,  128,  141,  142,  143,  144,
      147,  138,  145,  131,  146,  148,  155,  149,  147,  144,

      151,  152,  137,  153,  156,  276,  143,  158,  167,  157,
      155,  152,  139,  142,  149,  145,  151,  141,  148,  146,
      153,  154,  157,  162,  158,  159,  159,  160,  160,  156,
      163,  154,  170,  167,  168,  173,  176,  171,  175,  181,
      182,  187,  189,  200,  192,  190,  162,  193,  175,  181,
      192,  197,  194,  163,  173,  168,  170,  171,  190,  176,
      187,  197,  198,  199,  193,  182,  194,  189,  200,  201,
      203,  204,  205,  206,  209,  198,  216,  199,  215,  201,
      217,  204,  218,  205,  210,  210,  212,  212,  215,  219,
      206,  221,  222,  227,  203,  218,  224,  225,  226,  228,

      209,  230,  222,  227,  229,  217,  216,  275,  232,  224,
      221,  226,  274,  225,  229,  242,  233,  219,  232,  240,
      251,  227,  233,  252,  230,  255,  251,  258,  240,  228,
      257,  256,  242,  252,  261,  255,  232,  256,  259,  260,
      257,  262,  264,  265,  258,  269,  270,  271,  259,  260,
      272,  273,  268,  267,  266,  263,  254,  253,  261,  250,
      249,  248,  247,  246,  245,  262,  264,  265,  244,  243,
      269,  270,  271,  241,  239,  272,  278,  238,  278,  278,
      278,  278,  278,  280,  280,  237,  280,  281,  281,  236,
      281,  281,  281,  281,  282,  282,  282,  282,  282,  235,

      282,  283,  234,  283,  285,  231,  285,  223,  220,  214,
      208,  207,  202,  196,  195,  191,  188,  186,  185,  184,
      183,  180,  179,  178,  177,  174,  172,  169,  166,  165,
      164,  150,  140,  132,  119,  109,  108,  106,  105,  101,
      100,   96,   94,   91,   87,   79,   68,   48,   44,   43,
       15,   14,   12,    5,    2,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277,  277,  277,  277,  277,  277,
      277,  277,  277,  277,  277

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ifm-scan.l"
#define INITIAL 0
#line 2 "ifm-scan.l"
/* Lexical scanner */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <vars.h>

#include "ifm-main.h"
#include "ifm-util.h"
#include "ifm-parse.h"

#define MAX_INCLUDE 100

#define yywrap() 1

/* Include file stack */
static vlist *istack = NULL;

/* Include level */
static int ilevel = 0;

/* Internal string buffer */
static vbuffer *sbuf = NULL;

/* Internal functions */
static void push_include(char *file, int libflag);
static void pop_include(void);
#define INC 1

#line 620 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp = NULL, *yy_bp = NULL;
	register int yy_act;

#line 46 "ifm-scan.l"


#line 777 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 278 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 556 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 48 "ifm-scan.l"
; /* Ignore comments */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 50 "ifm-scan.l"
; /* Strip whitespace */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 52 "ifm-scan.l"
{
		    line_number++;
		}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 56 "ifm-scan.l"
{
		    int c, quote = 0, eatspace = 0;

                    /* Initialise buffer */
                    if (sbuf == NULL)
                        sbuf = vb_create();
                    else
                        vb_empty(sbuf);

		    /* Slurp string in, one char at a time */
		    while (1) {
                        c = input();

                        if        (c == EOF) {
                            yyerror("unterminated string");
                            break;
                        } else if (c == '"' && !quote) {
                            break;
                        } else if (c == '\\' && !quote) {
                            quote = 1;
                            continue;
                        } else if (c == '\n') {
                            vb_putc(sbuf, ' ');
                            eatspace = 1;
                            line_number++;
                        } else if (!eatspace || !isspace(c)) {
                            vb_putc(sbuf, c);
                        }

                        if (!isspace(c))
                            eatspace = 0;
                        quote = 0;
		    }

		    yylval.sval = vb_getcopy(sbuf);
		    return STRING;
		}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 94 "ifm-scan.l"
{ return AFTER; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 95 "ifm-scan.l"
{ return ALL; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 96 "ifm-scan.l"
{ return ANY; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 97 "ifm-scan.l"
{ return BEFORE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 98 "ifm-scan.l"
{ return CMD; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 99 "ifm-scan.l"
{ return DOWN; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 100 "ifm-scan.l"
{ return DIR; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 101 "ifm-scan.l"
{ return DOWN; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 102 "ifm-scan.l"
{ return DROP; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 103 "ifm-scan.l"
{ return EAST; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 104 "ifm-scan.l"
{ return EAST; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 105 "ifm-scan.l"
{ return ENDSTYLE; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 106 "ifm-scan.l"
{ return EXCEPT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 107 "ifm-scan.l"
{ return EXIT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 108 "ifm-scan.l"
{ return FINISH; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 109 "ifm-scan.l"
{ return FOLLOW; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 110 "ifm-scan.l"
{ return FROM; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 111 "ifm-scan.l"
{ return GET; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 112 "ifm-scan.l"
{ return GIVE; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 113 "ifm-scan.l"
{ return GIVEN; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 114 "ifm-scan.l"
{ return GO; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 115 "ifm-scan.l"
{ return GOTO; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 116 "ifm-scan.l"
{ return HIDDEN; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 117 "ifm-scan.l"
{ return IGNORE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 118 "ifm-scan.l"
{ return IN; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 119 "ifm-scan.l"
{ return IT; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 120 "ifm-scan.l"
{ return ITEM; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 121 "ifm-scan.l"
{ return JOIN; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 122 "ifm-scan.l"
{ return KEEP; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 123 "ifm-scan.l"
{ return LAST; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 124 "ifm-scan.l"
{ return LEAVE; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 125 "ifm-scan.l"
{ return LENGTH; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 126 "ifm-scan.l"
{ return LINK; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 127 "ifm-scan.l"
{ return LOSE; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 128 "ifm-scan.l"
{ return LOST; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 129 "ifm-scan.l"
{ return MAP; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 130 "ifm-scan.l"
{ return NORTH; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 131 "ifm-scan.l"
{ return NORTHEAST; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 132 "ifm-scan.l"
{ return NEED; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 133 "ifm-scan.l"
{ return NOLINK; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 134 "ifm-scan.l"
{ return NOPATH; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 135 "ifm-scan.l"
{ return NONE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 136 "ifm-scan.l"
{ return NORTH; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 137 "ifm-scan.l"
{ return NORTHEAST; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 138 "ifm-scan.l"
{ return NORTHWEST; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 139 "ifm-scan.l"
{ return NOTE; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 140 "ifm-scan.l"
{ return NORTHWEST; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 141 "ifm-scan.l"
{ return ONEWAY; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 142 "ifm-scan.l"
{ return OUT; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 143 "ifm-scan.l"
{ return PUZZLE; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 144 "ifm-scan.l"
{ return REQUIRE; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 145 "ifm-scan.l"
{ return ROOM; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 146 "ifm-scan.l"
{ return SOUTH; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 147 "ifm-scan.l"
{ return SAFE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 148 "ifm-scan.l"
{ return SCORE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 149 "ifm-scan.l"
{ return SOUTHEAST; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 150 "ifm-scan.l"
{ return SOUTH; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 151 "ifm-scan.l"
{ return SOUTHEAST; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 152 "ifm-scan.l"
{ return SOUTHWEST; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 153 "ifm-scan.l"
{ return SPECIAL; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 154 "ifm-scan.l"
{ return START; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 155 "ifm-scan.l"
{ return STYLE; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 156 "ifm-scan.l"
{ return SOUTHWEST; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 157 "ifm-scan.l"
{ return TAG; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 158 "ifm-scan.l"
{ return TASK; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 159 "ifm-scan.l"
{ return TIMES; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 160 "ifm-scan.l"
{ return TITLE; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 161 "ifm-scan.l"
{ return TO; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 162 "ifm-scan.l"
{ return UP; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 163 "ifm-scan.l"
{ return UNDEF; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 164 "ifm-scan.l"
{ return UNTIL; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 165 "ifm-scan.l"
{ return UP; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 166 "ifm-scan.l"
{ return WEST; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 167 "ifm-scan.l"
{ return WEST; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 168 "ifm-scan.l"
{ return WITH; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 170 "ifm-scan.l"
{
                    BEGIN(INC);
                }
	YY_BREAK
case 81:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 174 "ifm-scan.l"
{
                    v_chop(yytext);
                    push_include(&yytext[1], 0);
                    BEGIN(INITIAL);
                }
	YY_BREAK
case 82:
*yy_cp = yy_hold_char; /* undo effects of setting up yytext */
yy_c_buf_p = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yytext again */
YY_RULE_SETUP
#line 180 "ifm-scan.l"
{
                    v_chop(yytext);
                    push_include(&yytext[1], 1);
                    BEGIN(INITIAL);
                }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(INC):
#line 186 "ifm-scan.l"
{
                    if (ilevel == 0)
                        yyterminate();
                    else
                        pop_include();
                }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 193 "ifm-scan.l"
{
		    yylval.sval = v_strdup(yytext);
		    return ID;
		}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 198 "ifm-scan.l"
{
		    yylval.sval = v_strdup(yytext);
		    return ID;
		}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 203 "ifm-scan.l"
{
		    yylval.sval = v_strdup(&yytext[1]);
		    return VAR;
		}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 208 "ifm-scan.l"
{
                    yylval.dval = atof(yytext);
		    return REAL;
		}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 213 "ifm-scan.l"
{
		    yylval.ival = atoi(yytext);
		    return INTEGER;
		}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 218 "ifm-scan.l"
{ return ALIAS; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 220 "ifm-scan.l"
{ return yytext[0]; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 222 "ifm-scan.l"
ECHO;
	YY_BREAK
#line 1390 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 278 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 278 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 277);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 222 "ifm-scan.l"


/* Push include level */
static void
push_include(char *file, int libflag)
{
#ifdef FLEX_SCANNER
    YY_BUFFER_STATE buffer;
    vhash *idata;
    FILE *fp;

    /* Sanity check */
    if (ilevel == MAX_INCLUDE)
        fatal("include files nested too deeply (> %d)", MAX_INCLUDE);

    /* Store current include level */
    idata = vh_create();
    vh_sstore(idata, "FILE", ifm_input);
    vh_istore(idata, "LINE", line_number);
    vh_pstore(idata, "BUFFER", YY_CURRENT_BUFFER);

    /* Push it onto include stack */
    if (istack == NULL)
        istack = vl_create();
    vl_ppush(istack, idata);
    ilevel++;

    /* Go to new include file */
    fp = open_file(file, libflag, 1);
    buffer = yy_create_buffer(fp, YY_BUF_SIZE);
    yy_switch_to_buffer(buffer);
    line_number = 1;
#else
    warn("this version of IFM doesn't support `include'");
#endif
}

/* Pop include level */
static void
pop_include(void)
{
#ifdef FLEX_SCANNER
    YY_BUFFER_STATE buffer;
    vhash *idata;

    ilevel--;
    idata = vl_ppop(istack);
    strcpy(ifm_input, vh_sgetref(idata, "FILE"));
    line_number = vh_iget(idata, "LINE");

    yy_delete_buffer(YY_CURRENT_BUFFER);
    buffer = vh_pget(idata, "BUFFER");
    yy_switch_to_buffer(buffer);

    vh_destroy(idata);
#endif
}
